---
- name: Reiniciar servidores
  hosts: servidores
  become: true

  tasks:
    - name: Reiniciar servidor
      reboot:
        reboot_timeout: 300
      async: 0
      poll: 0
      ignore_errors: true

