---
- name: Update packages and check for reboot requirement
  hosts: all
  become: yes
  vars:
    ntfy_url: "https://ntfy.bnds.link/NJWeS1A7FZHj5bKQ"
    ntfy_token: "{{ token }}"
    

  tasks:
    - name: Bloque de actualización y verificación
      block:
        - name: Update packages with apt
          when: ansible_pkg_mgr == 'apt'
          ansible.builtin.apt:
            update_cache: true
          register: update_result

        - name: Enviar notificación si la actualización tuvo éxito
          command: >
            curl -H 'Authorization: Bearer {{ ntfy_token }}'
                 -H 'Title: Actualización exitosa en {{ ansible_hostname }}'
                 -H 'Priority: low'
                 -d 'Actualización de paquetes exitosa 😀'
                 {{ ntfy_url }}
          when: update_result.changed

        - name: Enviar notificación si hubo un error en la actualización
          command: >
            curl -H 'Authorization: Bearer {{ ntfy_token }}'
                 -H 'Title: Error en actualización en {{ ansible_hostname }}'
                 -H 'Priority: high'
                 -d 'Error al actualizar paquetes 😟'
                 {{ ntfy_url }}
          when: update_result.failed

        - name: Upgrade packages with apt
          when: ansible_pkg_mgr == 'apt'
          ansible.builtin.apt:
            upgrade: dist
          register: upgrade_result

        - name: Enviar notificación si la mejora tuvo éxito
          command: >
            curl -H 'Authorization: Bearer {{ ntfy_token }}'
                 -H 'Title: Mejora exitosa en {{ ansible_hostname }}'
                 -H 'Priority: low'
                 -d 'Mejora de paquetes exitosa 😀'
                 {{ ntfy_url }}
          when: upgrade_result.changed

        - name: Enviar notificación si hubo un error en la mejora
          command: >
            curl -H 'Authorization: Bearer {{ ntfy_token }}'
                 -H 'Title: Error en mejora en {{ ansible_hostname }}'
                 -H 'Priority: high'
                 -d 'Error al mejorar paquetes 😟'
                 {{ ntfy_url }}
          when: upgrade_result.failed

        - name: Check if system reboot is required
          when: ansible_pkg_mgr == 'apt'
          ansible.builtin.stat:
            path: /run/reboot-required
          register: reboot_required

        - name: Enviar notificación si el reinicio es necesario
          command: >
            curl -H 'Authorization: Bearer {{ ntfy_token }}'
                 -H 'Title: Reinicio necesario en {{ ansible_hostname }}'
                 -H 'Priority: low'
                 -d 'Reinicio del sistema necesario 🔄'
                 {{ ntfy_url }}
          when: reboot_required.stat.exists

        - name: Enviar notificación si el reinicio no es necesario
          command: >
            curl -H 'Authorization: Bearer {{ ntfy_token }}'
                 -H 'Title: Reinicio no necesario en {{ ansible_hostname }}'
                 -H 'Priority: low'
                 -d 'No es necesario reiniciar el sistema ❌'
                 {{ ntfy_url }}
          when: not reboot_required.stat.exists

        - name: Enviar notificación de éxito final
          command: >
            curl -H 'Authorization: Bearer {{ ntfy_token }}'
                 -H 'Title: Todas las tareas completadas en {{ ansible_hostname }}'
                 -H 'Priority: low'
                 -d 'Todas las tareas han sido ejecutadas con éxito 😀'
                 {{ ntfy_url }}

      rescue:
        - name: Enviar notificación si alguna tarea falla
          command: >
            curl -H 'Authorization: Bearer {{ ntfy_token }}'
                 -H 'Title: Error en tarea en {{ ansible_hostname }}'
                 -H 'Priority: high'
                 -d 'Error durante la ejecución del playbook ❌'
                 {{ ntfy_url }}