---
- name: Actualizar paquetes del sistema y reiniciar si es necesario
  hosts: all
  become: yes

  tasks:
    - name: Actualizar todos los paquetes del sistema
      apt:
        update_cache: yes
        upgrade: yes
      register: update_result

    - name: Reiniciar el servidor si es necesario
      reboot:
        reboot_timeout: 300
        test_command: uptime
      when: update_result.changed

    - name: Send Telegram message after update and upgrade
      community.general.telegram:
        token: "{{ telegram_bot_token }}"
        api_args:
          chat_id: "{{ telegram_chat_id }}"
          text: |
            Host: {{ ansible_hostname }}
            Ansible update and upgrade tasks finished.
            Update status: {{ 'success' if update_result.changed else 'no changes' }}
            Upgrade status: {{ 'success' if upgrade_result.changed else 'no changes' }}
      when: update_result.changed or upgrade_result.changed
