---
- name: Actualizar paquetes del sistema y reiniciar si es necesario
  hosts: all
  become: yes

  tasks:
    - name: Actualizar todos los paquetes del sistema
      apt:
        update_cache: yes
        upgrade: yes
      register: update_result

    - name: Reiniciar el servidor si es necesario
      reboot:
        reboot_timeout: 300
        test_command: uptime
      when: update_result.changed

    - name: Verificar si hubo actualizaciones
      set_fact:
        upgrade_available: "{{ update_result | changed }}"

    - name: Enviar mensaje de Telegram si hay actualizaciones
      community.general.telegram:
        token: "{{ telegram_bot_token }}"
        chat_id: "{{ telegram_chat_id }}"
        text: |
          Host: {{ ansible_hostname }}
          Ansible update and upgrade tasks finished.
          Update status: {{ 'success' if update_result.changed else 'no changes' }}
          {% if upgrade_available %}
          Upgrade status: Updates available
          {% else %}
          Upgrade status: No updates available
          {% endif %}
      when: update_result.changed or upgrade_available
