---
- name: Actualizar paquetes del sistema y reiniciar si es necesario
  hosts: all
  become: yes

  tasks:
    - name: Actualizar todos los paquetes del sistema
      apt:
        update_cache: yes
        upgrade: yes
      register: update_result

    - name: revisar si es necesario reiniciar
    ansible.builtin.stat:
      path: /var/run/reboot-required
      get_checksum: no
    register: reboot_required_file

    - name: reiniciar (si es necesario)
      ansible.builtin.reboot:
        test_command: uptime
      when: reboot_required_file.stat.exists == true
      register: reboot_result
      
    - name: remover dependencias que no son necesarias.
      ansible.builtin.apt:
        autoremove: yes

    # - name: Reiniciar el servidor solo si es necesario
    #   reboot:
    #     reboot_timeout: 300
    #     test_command: uptime
    #   register: reboot_result

    - name: Enviar notificación si la actualización tuvo éxito
      command: "curl -H 'Authorization: Bearer {{ token }}' -H 'Title: Actualización exitosa en {{ ansible_hostname }}' -H 'Priority: low' -d 'Actualización de paquetes exitosa 😀' https://ntfy.bnds.link/upgrade"
      when: update_result.changed

    - name: Enviar notificación si hubo un error en la actualización
      command: "curl -H 'Authorization: Bearer {{ token }}' -H 'Title: Error en actualización en {{ ansible_hostname }}' -H 'Priority: high' -d 'Error al actualizar paquetes 😟' https://ntfy.bnds.link/upgrade"
      when: update_result.failed

    - name: Enviar notificación si el reinicio fue necesario y tuvo éxito
      command: "curl -H 'Authorization: Bearer {{ token }}' -H 'Title: Reinicio exitoso en {{ ansible_hostname }}' -H 'Priority: low' -d 'Servidor reiniciado correctamente 🔄' https://ntfy.bnds.link/upgrade"
      when: reboot_result.rebooted

    - name: Enviar notificación si hubo un error en el reinicio
      command: "curl -H 'Authorization: Bearer {{ token }}' -H 'Title: Error en reinicio en {{ ansible_hostname }}' -H 'Priority: high' -d 'Error al reiniciar el servidor ❌' https://ntfy.bnds.link/upgrade"
      when: reboot_result.failed
