- name: Actualizar paquetes del sistema y reiniciar
  hosts: all
  become: yes
  become_user: bnds
  become_method: sudo
   
  tasks:
    - name: Actualizar todos los paquetes del sistema
      apt:
        update_cache: yes
        upgrade: yes

    - name: Reiniciar el servidor
      reboot:
        reboot_timeout: 300
        test_command: uptime