---
- name: Actualizar paquetes del sistema y reiniciar si es necesario
  hosts: all
  become: yes

  tasks:
    - name: Actualizar todos los paquetes del sistema
      apt:
        update_cache: yes
        upgrade: yes
      register: update_result

    - name: Reiniciar el servidor solo si es necesario
      reboot:
        reboot_timeout: 300
        test_command: uptime
      register: reboot_result

    - name: Enviar notificación si la actualización tuvo éxito
      command: "curl -H 'Title: Actualización exitosa' -H 'Priority: low' -d 'Actualización de paquetes exitosa 😀' http://ntfy.lc.bnds.link/upgrade"
      when: update_result.changed

    - name: Enviar notificación si hubo un error en la actualización
      command: "curl -H 'Title: Error en actualización' -H 'Priority: high' -d 'Error al actualizar paquetes 😟' http://ntfy.lc.bnds.link/upgrade"
      when: update_result.failed

    - name: Enviar notificación si el reinicio fue necesario y tuvo éxito
      command: "curl -H 'Title: Reinicio exitoso' -H 'Priority: low' -d 'Servidor reiniciado correctamente 🔄' http://ntfy.lc.bnds.link/upgrade"
      when: reboot_result.stdout.find("rebooted") != -1

    - name: Enviar notificación si hubo un error en el reinicio
      command: "curl -H 'Title: Error en reinicio' -H 'Priority: high' -d 'Error al reiniciar el servidor ❌' http://ntfy.lc.bnds.link/upgrade"
      when: reboot_result.failed
